main: io.github.winx64.sse.SmartSignEditor
name: ${project.name}
description: ${project.description}
version: ${project.version}
author: '123'
website: ${project.url}

commands:
    sse:
        description: Gives yourself the sign handling tool
        usage: /<command>
        aliases: [smartsigneditor]
        permission: sse.command.sse
    sse-reload:
        description: Reloads the plugin configuration
        usage: /<command>
        aliases: [sreload, ssereload]
        permission: sse.command.reload

permissions:
    sse.*:
        description: Complete access to SmartSignEditor
        children:
            sse.command.sse: true
            sse.command.reload: true
            sse.tool.extended: true
            sse.tool.override: true
            sse.tool.edit: true
            sse.tool.edit.colors: true
            sse.tool.copy: true
            sse.tool.copy.all: true
            sse.tool.copy.line: true
            sse.tool.copy.colors: true
            sse.tool.paste: true
            sse.tool.paste.all: true
            sse.tool.paste.line: true
            sse.tool.paste.colors: true
            sse.tool.erase: true
            sse.tool.erase.all: true
            sse.tool.erase.line: true
        default: op
        
    sse.command.*:
        description: Complete access to every command
        children:
            sse.command.sse: true
            sse.command:reload: true
        default: op
        
    sse.tool.*:
        description: Complete access to every tool
        children:
            sse.tool.extended: true
            sse.tool.override: true
            sse.tool.edit: true
            sse.tool.edit.colors: true
            sse.tool.copy: true
            sse.tool.copy.all: true
            sse.tool.copy.line: true
            sse.tool.copy.colors: true
            sse.tool.paste: true
            sse.tool.paste.all: true
            sse.tool.paste.line: true
            sse.tool.paste.colors: true
            sse.tool.erase: true
            sse.tool.erase.all: true
            sse.tool.erase.line: true
        default: op
        
    sse.tool.edit.*:
        description: Complete access to the Edit Tool
        children:
            sse.tool.edit: true
            sse.tool.edit.colors: true
        default: op
        
    sse.tool.copy.*:
        description: Complete access to the Copy Tool
        children:
            sse.tool.copy: true
            sse.tool.copy.all: true
            sse.tool.copy.line: true
            sse.tool.copy.colors: true
        default: op
        
    sse.tool.paste.*:
        description: Complete access to the Paste Tool
        children:
            sse.tool.paste: true
            sse.tool.paste.all: true
            sse.tool.paste.line: true
            sse.tool.paste.colors: true
        default: op
        
    sse.tool.erase.*:
        description: Complete access to the Erase Tool
        children:
            sse.tool.erase: true
            sse.tool.erase.all: true
            sse.tool.erase.line: true
        default: op